// src/features/posts/components/PostCard.tsx
import * as React from 'react';
import { Post } from '@/features/posts/types';
import { Link } from 'react-router-dom';
import { MDPreview } from '@/components/Elements';

export type PostCardProps = {
  post: Post;
};

export const PostCard = ({ post }: PostCardProps) => {
  if (!post) {
    return null;
  }

  return (
    <div className="w-full lg:max-w-full lg:flex mb-4">
      <div className="w-full border border-gray-400 lg:border-gray-400 bg-white rounded-b p-4 flex flex-col justify-between leading-normal">
        <div className="mb-8">
          <Link to={`./${post.slug}`} className="text-gray-900 font-bold text-xl mb-2">
            {post.title}
          </Link>

          <div className="text-gray-700 text-base overflow-hidden line-clamp-3">
            <MDPreview value={post.body} />
          </div>
        </div>

        <div className="flex items-center">
          <div className="text-sm">
            <p className="text-gray-900 leading-none">{post.author}</p>
            <p className="text-gray-600">{post.createdAt}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

// src/domain/post/components/PostCard.vue
<template>
    <div class="bg-white shadow-2xl rounded-lg mb-6 tracking-wide" >
      <div class="px-4 py-2 mt-2">
        <h2 class="font-bold text-2xl px-2 py-2 text-gray-800 tracking-normal">
          {{ post.title }}
        </h2>

        <p class="text-sm text-gray-700 px-2" v-html="post.body"></p>

        <div class="flex items-center justify-between mt-2 mx-6">
          <a href="#" class="text-blue-500 text-xs -ml-3 ">Show More</a>
        </div>

        <div class="author flex items-center -ml-3 my-3">
          <h2 class="text-sm tracking-tighter text-gray-900">
            <a href="#">By {{ post.author }}</a>
            <span class="text-gray-600">{{ post.createdAt }}</span>
          </h2>
        </div>
      </div>
  </div>
</template>
<script lang="ts">
/* eslint-disable no-unused-vars */
import { Post } from '@/domain/post/models/post.model'
import { PropType, defineComponent } from 'vue'
/* eslint-enable no-unused-vars */

export default defineComponent({
  props: {
    post: {
      type: Object as PropType<Post>,
      required: true
    }
  }
})
</script>
