// src/components/Elements/Button/Button.tsx
import clsx from 'clsx';
import * as React from 'react';

import { Spinner } from '@/components/Elements/Spinner';

const variants = {
    primary: 'bg-blue-600 text-white hover:bg-gray-50:text-blue-600',
    inverse: 'bg-white text-blue-600 hover:bg-blue-600:text-white',
    danger: 'bg-red-600 text-white hover:bg-red-50:text-red-600',
};

const sizes = {
    sm: 'py-2 px-4 text-sm',
    md: 'py-2 px-6 text-md',
    lg: 'py-3 px-8 text-lg',
};

type IconProps =
    | { startIcon: React.ReactElement; endIcon?: never }
    | { endIcon: React.ReactElement; startIcon?: never }
    | { endIcon?: undefined; startIcon?: undefined };

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
    variant?: keyof typeof variants;
    size?: keyof typeof sizes;
    isLoading?: boolean;
} & IconProps;

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
    (
        {
            type = 'button',
            className = '',
            variant = 'primary',
            size = 'md',
            isLoading = false,
            startIcon,
            endIcon,
            ...props
        },
        ref
    ) => {
        return (
            <button
                ref={ref}
                type={type}
                className={clsx(
                    'flex justify-center items-center border border-gray-300 disabled:opacity-70 disabled:cursor-not-allowed rounded-md shadow-sm font-medium focus:outline-none',
                    variants[variant],
                    sizes[size],
                    className
                )}
                {...props}
            >
                {isLoading && <Spinner size="sm" className="text-current" />}
                {!isLoading && startIcon}
                <span className="mx-2">{props.children}</span> {!isLoading && endIcon}
            </button>
        );
    }
);

Button.displayName = 'Button';

// src/domain/shared/components/button/Button.vue
<template>
  <button
      :type="type"
      class="g-btn"
      :class="[
      variant ? `g-btn-${variant}` : 'g-btn-primary',
      outlined && `g-btn-${variant}-outlined`,
      size && `g-btn-${size}`,
      rounded && 'rounded-full',
      block && 'g-btn-block',
      text && 'g-btn-text',
    ]"
      :disabled="disabled"
  >
    <slot></slot>
  </button>
</template>
<script lang="ts">
import {defineComponent} from "vue";

enum Variants {
  Primary = "primary",
  Secondary = "secondary",
  Success = "success",
  Info = "info",
  Warning = "warning",
  Danger = "danger",
}

enum Sizes {
  Sm = "sm",
  Md = "md",
  Lg = "lg",
  OneXl = "xl",
  TwoXl = "2xl",
}

export default defineComponent({
  name: "g-button",

  props: {
    variant: {
      type: String,
      validator: (value: Variants) =>
          [
            Variants.Primary,
            Variants.Secondary,
            Variants.Success,
            Variants.Info,
            Variants.Warning,
            Variants.Danger,
          ].includes(value),
    },
    size: {
      type: String,
      validator: (value: Sizes) =>
          [Sizes.Sm, Sizes.Md, Sizes.Lg, Sizes.OneXl, Sizes.TwoXl].includes(
              value
          ),
    },
    type: {type: String, default: "button"},
    rounded: Boolean,
    disabled: Boolean,
    outlined: Boolean,
    block: Boolean,
    text: Boolean,
  },

  setup() {
    return {};
  },
});
</script>
<style lang="scss" scoped>
$button-variants: (
    (
        "variant": "primary",
        "color": text-white,
        "background": indigo-900,
        "border": indigo-700,
        "hover": indigo-600,
        "outline": indigo-900,
    ),
    (
        "variant": "secondary",
        "color": text-white,
        "background": gray-900,
        "border": gray-700,
        "hover": gray-600,
        "outline": gray-900,
    ),
    (
        "variant": "success",
        "color": text-white,
        "background": green-500,
        "border": green-900,
        "hover": green-600,
        "outline": green-500,
    ),
    (
        "variant": "info",
        "color": text-white,
        "background": blue-500,
        "border": blue-900,
        "hover": blue-600,
        "outline": blue-500,
    ),
    (
        "variant": "warning",
        "color": text-white,
        "background": yellow-500,
        "border": yellow-900,
        "hover": yellow-600,
        "outline": yellow-500,
    ),
    (
        "variant": "danger",
        "color": text-white,
        "background": red-500,
        "border": red-900,
        "hover": red-600,
        "outline": red-500,
    )
);

@mixin button-variant-outlined($outline, $color, $hover) {
  @apply bg-opacity-0;
  @apply hover:bg-#{$hover} hover:#{$color} hover:border-#{$hover};
  @apply text-#{$outline};
  @apply border-#{$outline};
}

@mixin button-variant($color, $background, $border, $hover, $outline) {
  @apply bg-#{$background};
  @apply hover:bg-#{$hover};
  @apply active:bg-#{$border};
  @apply focus:outline-none focus:border-#{$border} focus:ring;
  @apply #{$color};

  &-outlined {
    @include button-variant-outlined($outline, $color, $hover);
  }
}

$text-sizes: sm, md, lg, xl, 2xl;

.g-btn {
  @apply inline-flex items-center tracking-widest border;
  @apply px-4 py-2;
  @apply transition ease-in-out duration-150;
  @apply font-semibold text-xs;

  @each $text-size in $text-sizes {
    @if $text-size == "md" {
      &-#{$text-size} {
        @apply text-base;
      }
    } @else {
      &-#{$text-size} {
        @apply text-#{$text-size};
      }
    }
  }

  @each $button-variant in $button-variants {
    $variant: map-get($button-variant, "variant");
    $color: map-get($button-variant, "color");
    $background: map-get($button-variant, "background");
    $border: map-get($button-variant, "border");
    $hover: map-get($button-variant, "hover");
    $outline: map-get($button-variant, "outline");

    &-#{$variant} {
      @include button-variant($color, $background, $border, $hover, $outline);
    }
  }

  &-text {
    @apply border-none shadow-none text-black hover:underline;
    @apply bg-transparent hover:bg-transparent hover:text-black focus:bg-transparent;
  }

  &-block {
    @apply block w-full;
  }
}
</style>
